# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2a74e7e6a6a67b161a259d7af7087f69c1af5c162e1ef7c75d527732d76cf4acda40b39222876e02c5b47b70e2adf186ed590ad87e8e74c199cbc56960a1f30

test:
  secret_key_base: 16f072d6909178fbb5ae6f1f29b3ea4280dceb8be4da9fbe1f91e8f9c18003390b537d04702db819a59922734803f7df3ad05446f6242c1f93626be8b828e91b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
